apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-deployment
spec:
  selector:
    matchLabels:
      name: mypod
  template:
    metadata:
      name: hello-world-pod
      labels: 
        name: mypod
    spec:
      containers:
        - name: hello-blue
          image: fatihmms/hello-blue
  replicas: 3