apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      name: hello-world-pod
      labels:
        app: blue
    spec:
        containers:
        - name: hello-blue
          image: fatihmms/hello-blue
  replicas: 3