apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-green-deployment
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      name: hello-green-pod
      labels:
        app: green
    spec:
        containers:
        - name: hello-green
          image: fatihmms/hello-blue:v1
  replicas: 3